apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-web
  name: deploy-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-web
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}


---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-web
    argocd.argoproj.io/instance: testargo
  name: deploy-web
spec:
  ports:
  - port: 90
    protocol: TCP
    targetPort: 90
  selector:
    app: deploy-web
  type: NodePort
status:
  loadBalancer: {}


