apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-web
  name: deploy-web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deploy-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-web
    spec:
      containers:
      - imagez: nginx
        name: nginx
        resources: {}
status: {}
