apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-web
    argocd.argoproj.io/instance: testargo
  name: deploy-web
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: deploy-web
  type: NodePort
status:
  loadBalancer: {}
