apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy1-web
  name: deploy1-web
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: deploy1-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy1-web
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}


